---
containerd_release_version: 1.6.15
cni_bin_dir: /opt/cni/bin/
cni_conf_dir: /etc/cni/net.d/
kubernetes_version: 1.26.0-00

containerd_package: containerd.io
containerd_package_state: present

# Service options.
containerd_service_state: started
containerd_service_enabled: true

# Write a default containerd config.toml file.
containerd_config_default_write: true

# Set systemd as cgroup driver in config.toml
# Only use with containerd_config_default_write: true
containerd_config_cgroup_driver_systemd: true